http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  # see: http://www.express-gateway.io/docs/configuration/gateway.config.yml/apiEndpoints
  customerApi:
    host: "*"
    paths: "/gateway/api/customers/*"
  vehicleApi:
    host: "*"
    paths: "/gateway/api/vehicles/*"
  driverApi:
    host: "*"
    paths: "/gateway/api/drivers/*"
  incidentApi:
    host: "*"
    paths: "/gateway/api/incidents/*"
  rateApi:
    host: "*"
    paths: "/gateway/api/rate_issue/rate/*"
  issueApi:
    host: "*"
    paths: "/gateway/api/rate_issue/issue/*"
  newIssueApi:
    host: "*"
    paths: "/gateway/policy/issue/*"
  inquiryApi:
    host: "*"
    paths: "/gateway/api/policy/inquiry/*"
serviceEndpoints:
  # see: http://www.express-gateway.io/docs/configuration/gateway.config.yml/serviceEndpoints
  customerSvc:
    url: "http://istio-ingressgateway-istiosystem.apps.openshift.ne-innovation.com"
  vehicleSvc:
    url: "http://istio-ingressgateway-istiosystem.apps.openshift.ne-innovation.com"
  driverSvc:
    url: "http://istio-ingressgateway-istiosystem.apps.openshift.ne-innovation.com"
  incidentSvc:
    url: "http://istio-ingressgateway-istiosystem.apps.openshift.ne-innovation.com"
  rateSvc:
    url: "http://istio-ingressgateway-istiosystem.apps.openshift.ne-innovation.com"
  issueSvc:
    url: "http://istio-ingressgateway-istiosystem.apps.openshift.ne-innovation.com"
  newIssueSvc:
    url: "http://istio-ingressgateway-istiosystem.apps.openshift.ne-innovation.com"
  inquirySvc:
    url: "http://istio-ingressgateway-istio-system.apps.azureocp.neinnovation-ocp.com"
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  # see: https://www.express-gateway.io/docs/configuration/gateway.config.yml/pipelines
  customer:
    apiEndpoints:
      - customerApi
    policies:
      - cors:
          - action:
              origin: true
      - expression:
          - action:
              jscode: 'req.url = req.url.replace("/gateway","");'
      - proxy:
          - action:
              serviceEndpoint: customerSvc
  vehicle:
    apiEndpoints:
      - vehicleApi
    policies:
      - cors:
          - action:
              origin: true
      - expression:
          - action:
              jscode: 'req.url = req.url.replace("/gateway","");'
      - proxy:
          - action:
              serviceEndpoint: vehicleSvc
  driver:
    apiEndpoints:
      - driverApi
    policies:
      - cors:
          - action:
              origin: true
      - expression:
          - action:
              jscode: 'req.url = req.url.replace("/gateway","");'
      - proxy:
          - action:
              serviceEndpoint: driverSvc
  incident:
    apiEndpoints:
      - incidentApi
    policies:
      - cors:
          - action:
              origin: true
      - expression:
          - action:
              jscode: 'req.url = req.url.replace("/gateway","");'
      - proxy:
          - action:
              serviceEndpoint: incidentSvc
  rate:
    apiEndpoints:
      - rateApi
    policies:
      - cors:
          - action:
              origin: true
      - expression:
          - action:
              jscode: 'req.url = req.url.replace("/gateway","");'
      - proxy:
          - action:
              serviceEndpoint: rateSvc
  issue:
    apiEndpoints:
      - issueApi
    policies:
      - cors:
          - action:
              origin: true
      - expression:
          - action:
              jscode: 'req.url = req.url.replace("/gateway","");'
      - proxy:
          - action:
              serviceEndpoint: issueSvc
  newIssueSvc:
    apiEndpoints:
      - newIssueApi
    policies:
      - cors:
          - action:
              origin: true
      - expression:
          - action:
              jscode: 'req.url = req.url.replace("/gateway","");'
      - proxy:
          - action:
              serviceEndpoint: newIssueSvc
  inquirySvc:
    apiEndpoints:
      - inquiryApi
    policies:
      - cors:
          - action:
              origin: true
      - expression:
          - action:
              jscode: 'req.url = req.url.replace("/gateway","");'
      - proxy:
          - action:
              serviceEndpoint: inquirySvc
