http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  # see: http://www.express-gateway.io/docs/configuration/gateway.config.yml/apiEndpoints
  customerApi:
    host: '*'
    paths: '/api/customers/*'
  vehicleApi:
    host: '*'
    paths: '/api/vehicles/*'
  driverApi:
    host: '*'
    paths: '/api/drivers/*'
  incidentApi:
    host: '*'
    paths: '/api/incidents/*'
  rateApi:
    host: '*'
    paths: '/api/rate_issue/rate/*'
  issueApi:
    host: '*'
    paths: '/api/rate_issue/issue/*'
  inquiryApi:
    host: '*'
    paths: '/api/policy/PolicyInquiry/*'
serviceEndpoints:
  # see: http://www.express-gateway.io/docs/configuration/gateway.config.yml/serviceEndpoints
  customerSvc:
    url: "http://customer-info-api-development.apps.openshift.ne-innovation.com"
  vehicleSvc:
    url: "http://vehicles-api-development.apps.openshift.ne-innovation.com"
  driverSvc:
    url: "http://drivers-api-development.apps.openshift.ne-innovation.com"
  incidentSvc:

    url: "http://incidents-api-development.apps.openshift.ne-innovation.com"
  rateSvc:
    url: "http://rate-api-development.apps.openshift.ne-innovation.com"
  issueSvc:
    url: "http://issue-api-development.apps.openshift.ne-innovation.com"
  inquirySvc:
    url: "http://policy-inquiry-api-development.apps.azureocp.neinnovation-ocp.com/gateway"
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  # see: https://www.express-gateway.io/docs/configuration/gateway.config.yml/pipelines
  customer:
    apiEndpoints:
      - customerApi
    policies:
      -
        cors:
          -
            action:
              origin: true
      -
        proxy:
          - 
            action:
              serviceEndpoint: customerSvc
  vehicle:
    apiEndpoints:
      - vehicleApi
    policies:
      -
        cors:
          -
            action:
              origin: true
      -
        proxy:
          - 
            action:
              serviceEndpoint: vehicleSvc
  driver:
    apiEndpoints:
      - driverApi
    policies:
      -
        cors:
          -
            action:
              origin: true
      -
        proxy:
          - 
            action:
              serviceEndpoint: driverSvc
  incident:
    apiEndpoints:
      - incidentApi
    policies:
      -
        cors:
          -
            action:
              origin: true
      -
        proxy:
          - 
            action:
              serviceEndpoint: incidentSvc
  rate:
    apiEndpoints:
      - rateApi
    policies:
      -
        cors:
          -
            action:
              origin: true
      -
        proxy:
          - 
            action:
              serviceEndpoint: rateSvc
  issue:
    apiEndpoints:
      - issueApi
    policies:
      -
        cors:
          -
            action:
              origin: true
      -
        proxy:
          - 
            action:
              serviceEndpoint: issueSvc
  inquiry:
    apiEndpoints:
      - inquiryApi
    policies:
      -
        cors:
          -
            action:
              origin: true
      -
        proxy:
          - 
            action:
              serviceEndpoint: inquirySvc